### PR TITLE
Sos ghazaryan homework 15 01 2024

### PR DESCRIPTION
**Pull request by sos24**

### CODE REVIEW

**Review by shtajiryan — CHANGES_REQUESTED** [review]
Currently the folder structure is like this. Repository -> homework-20-12-23 -> sos-ghazaryan -> homework-15-01-2024 and so on. Is this not the classwork? If so fix the folder and file structure, otherwise let me know in Slack!

**Comment by sos24** [comment]
I have changed the files structure

**Review by shtajiryan — CHANGES_REQUESTED** [review]
Because of .gitignore the .env file is missing.

WARN[0000] The "DB_ROOT_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DB_ROOT_PASSWORD" variable is not set. Defaulting to a blank string. 
env file /home/shtajiryan/repos/devops-hti-2023/classwork-13-01-2024/sos-ghazaryan/.env not found

I created a .env file locally with DB_ROOT_PASSWORD inside and everything works.

1. instead of taking the DB_ROOT_PASSWORD from an .env file you can write it into the code, as this is a test environment.
2. remove .env from .gitignore and make another commit with the .env file included.

the first option is not best practice, but as this is a test environment, it's okay to do so.

**Review by shtajiryan — CHANGES_REQUESTED** [review]
WARN[0000] The "DB_ROOT_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DB_ROOT_PASSWORD" variable is not set. Defaulting to a blank string. 

because of .env file is included in .gitignore, it did not get pushed to the repo.
option 1. remove .env from .gitignore and make another commit
option 2. include DB_ROOT_PASSWORD in plain text here:

      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="${DB_ROOT_PASSWORD}" --silent' ]
      
as this is a test environment, it won't hurt to put the password here.

It is not best practice to put the password in plain text inside the code, but for this test environment it will be okay

**Comment by sos24** [comment]
> WARN[0000] The "DB_ROOT_PASSWORD" variable is not set. Defaulting to a blank string. WARN[0000] The "DB_ROOT_PASSWORD" variable is not set. Defaulting to a blank string.
> 
> because of .env file is included in .gitignore, it did not get pushed to the repo. option 1. remove .env from .gitignore and make another commit option 2. include DB_ROOT_PASSWORD in plain text here:
> 
> ```
>   test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="${DB_ROOT_PASSWORD}" --silent' ]
> ```
> 
> as this is a test environment, it won't hurt to put the password here.
> 
> It is not best practice to put the password in plain text inside the code, but for this test environment it will be okay

I have added  .env file

**Review by shtajiryan — APPROVED** [review]

**Pull request merged**
